"""Initial Migration

Revision ID: 59cd7aeb4016
Revises: a01eb3862168
Create Date: 2022-05-12 09:12:45.674583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cd7aeb4016'
down_revision = 'a01eb3862168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###
