"""Initial Migration

Revision ID: a01eb3862168
Revises: 
Create Date: 2022-05-12 01:01:36.275284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01eb3862168'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('pitch', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'full_time')
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'user_id')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'pitch')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'id')
    # ### end Alembic commands ###
